name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/django-app

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 mypy pytest

      - name: Static code analysis - flake8
        run: flake8 .

      - name: Static type checking - mypy
        run: mypy .

      - name: Run unit tests
        run: pytest tests/unit --maxfail=1 --disable-warnings -q

      - name: Run integration tests
        run: pytest tests/integration --maxfail=1 --disable-warnings -q

      - name: Run acceptance tests
        run: pytest tests/acceptance --maxfail=1 --disable-warnings -q

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

  post_release_tasks:
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Notify Slack about successful release
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "Django-app successfully built and released! Docker image pushed: ${{ env.IMAGE_NAME }}:latest",
              "attachments": [
                {
                  "color": "good",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Create Jira comment about release
        if: ${{ secrets.JIRA_API_TOKEN && secrets.JIRA_BASE_URL && secrets.JIRA_USER_EMAIL }}
        uses: atlassian/gajira-comment@v3
        with:
          issue: YOURPROJECT-RELEASE
          body: "Release successful: commit ${{ github.sha }} on branch main. Docker image: ${{ env.IMAGE_NAME }}:latest"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
